include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

stages:
- lint
- test

lint:
  stage: lint
  image: python:3.8.16
  before_script:
  - echo $PATH
  - wget https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz
  - gunzip rye-x86_64-linux.gz
  - chmod +x ./rye-x86_64-linux
  - ./rye-x86_64-linux
  - rye sync
  script:
  - rye lint

sast:
  stage: test
