stages:
- build
- check

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.10.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
      --cache=true --cache-copy-layers=true --cache-ttl=24h --cache-run-layers=true
  rules:
    - if: $CI_COMMIT_BRANCH
      when: on_success

check:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  stage: check
  before_script:
    - rye sync
  script:
    - rye run check
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ".cache"
