include:
- template: Security/SAST.gitlab-ci.yml

stages:
- lint
- test

lint:
  stage: lint
  image: python:3.8
  before_script:
    - pip3 install -r requirements-dev.lock
  script:
    - black src
    - flake8 src
    - mypy src

sast:
  stage: test
