stages:
- lint
- test

default:
  image: python:3.8.16
  before_script:
  - pip3 install -r requirements-dev.lock
  - wget https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz
  - gunzip rye-x86_64-linux.gz
  - chmod +x ./rye-x86_64-linux
  - ./rye-x86_64-linux --version

lint:
  stage: lint
  script:
  - black --check src
  - pflake8 src
  - pylint src
  - mypy src
