stages:
- build
- lint

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.10.0
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - Dockerfile
        - requirements-dev.lock
        - pyproject.toml
  
# lint:
#   stage: lint
#   script:
#   - rye run lint
