stages:
- lint
- test

default:
  image: python:3.8.16
  before_script:
  - pip3 install -r requirements-dev.lock
  - wget https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz
  - gunzip rye-x86_64-linux.gz
  - mv ./rye* /usr/local/bin/rye
  - chmod +x /usr/local/bin/rye
  - rye --version
  - rye sync

lint:
  stage: lint
  script:
  - rye run lint
