stages:
- build
- lint

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
      --cache=true --cache-copy-layers=true --cache-ttl=24h --cache-run-layers=true
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - .gitlab-ci.yml
        - Dockerfile
        - requirements-dev.lock
        - pyproject.toml
  
# lint:
#   stage: lint
#   script:
#   - rye run lint
