include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

stages:
- lint
- test

lint:
  stage: lint
  image: python:3.8.16
  before_script:
  - curl -sSf https://rye-up.com/get | bash
  - rye sync
  script:
  - rye lint

sast:
  stage: test
